// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
)

var (
	Q       = new(Query)
	Address *address
	Hobby   *hobby
	User    *user
)

func SetDefault(db *gorm.DB) {
	*Q = *Use(db)
	Address = &Q.Address
	Hobby = &Q.Hobby
	User = &Q.User
}

func Use(db *gorm.DB) *Query {
	return &Query{
		db:      db,
		Address: newAddress(db),
		Hobby:   newHobby(db),
		User:    newUser(db),
	}
}

type Query struct {
	db *gorm.DB

	Address address
	Hobby   hobby
	User    user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:      db,
		Address: q.Address.clone(db),
		Hobby:   q.Hobby.clone(db),
		User:    q.User.clone(db),
	}
}

type queryCtx struct {
	Address IAddressDo
	Hobby   IHobbyDo
	User    IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Address: q.Address.WithContext(ctx),
		Hobby:   q.Hobby.WithContext(ctx),
		User:    q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	return &QueryTx{q.clone(q.db.Begin(opts...))}
}

type QueryTx struct{ *Query }

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
