// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameHobby = "hobby"

// Hobby mapped from table <hobby>
type Hobby struct {
	ID        int64  `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	Name      string `gorm:"column:name;type:varchar(20);not null" json:"name"`
	UpdatedAt int64  `gorm:"column:updated_at;type:int unsigned;not null" json:"updated_at"`
	CreatedAt int64  `gorm:"column:created_at;type:int unsigned;not null" json:"created_at"`
	DeletedAt int64  `gorm:"column:deleted_at;type:int unsigned;not null" json:"deleted_at"`
}

// TableName Hobby's table name
func (*Hobby) TableName() string {
	return TableNameHobby
}
